config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :researchers
  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :items, only: [:show, :index, :new, :create, :edit, :update]

  resources :tags, only: [:index, :show, :edit, :update, :destroy], param: :name
  get 'tags/:name', to: 'tags#show', as: 'gutentag_tag'

  resources :entities, only: [:edit, :update, :new, :create], param: :slug

  resources :industry_associations, only: [:index, :show], param: :slug do
    resources :memberships, only: [:new, :create]
    resources :members, only: [:index], controller: 'memberships'
  end

  resources :companies, only: [:index, :show], param: :slug do
    resources :memberships, only: [:index, :new, :create]
  end

  resources :memberships, only: [:edit, :update]

  get 'staging', to: 'staging#index'

  namespace :staging do
    get 'dismissed', to: 'dismissed#index'

    resources :feeds, only: [:index] do
      post 'activate', on: :member, to: 'feeds#activate'
      post 'pause', on: :member, to: 'feeds#pause'
      post 'webhook', on: :member, to: 'feeds#webhook'
    end
  end

  post 'staging_items/:id/dismiss', to: 'staging#dismiss', as: 'dismiss_staging_item'

  namespace :api do
    namespace :v0 do
      resources :items, only: [:index]
    end
  end

  authenticate :researcher do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :company
  belongs_to :industry_association

  # Don't allow duplicates
  validates(:company_id, uniqueness: { scope: :industry_association_id })
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action(
    :authenticate_researcher!,
    unless: -> { ENV['PUBLIC_ACCESS'].eql?('true') && ['index'].include?(action_name) }
  )
  before_action(:authenticate_editor!, except: [:index])
  before_action :use_minimal_layout, only: [:new, :edit]

  def index
    @entity = Entity.includes(:memberships).find_by_slug!(entity_param_for_type)

    @memberships_with_entities =
      if @entity.company?
        @entity.memberships.map {|m| [m, m.industry_association] }
      elsif @entity.industry_association?
        @entity.memberships.map {|m| [m, m.company] }
      end

    @memberships_with_entities.sort! {|a,b| a[1]&.name <=> b[1]&.name }
  end

  def new
    @entity = Entity.find_by_slug!(entity_param_for_type)

    @membership =
      if @entity.company?
        Membership.new(company: @entity)
      elsif @entity.industry_association?
        Membership.new(industry_association: @entity)
      end

    assign_return_to(@entity)
  end

  def create
    @entity = Entity.find_by_slug!(entity_param_for_type)
    @membership = @entity.memberships.new(membership_params)

    assign_return_to(@entity)

    if @membership.save
      redirect_to @entity, notice: "Successfully added industry association membership"
    else
      flash.now[:error] = "We could not to save this membership."
      render :new
    end
  end

  def edit
    @membership = Membership.find(params[:id])
    @lead_entity_type = params[:t] if ['Company', 'IndustryAssociation'].include?(params[:t])
  end

  def update
    @membership = Membership.find(params[:id])

    if @membership.update(edit_membership_params)
      if params[:lead_entity_type].eql? 'Company'
        redirect_to company_memberships_path(@membership.company)
      elsif params[:lead_entity_type].eql? 'IndustryAssociation'
        redirect_to industry_association_members_path(@membership.industry_association)
      else
        flash.now[:error] = "We could not to save these changes. Copy the URL and let Luke know you saw this."
        render :edit
      end
    else
      flash.now[:error] = "We could not to save these changes."
      render :edit
    end
  end

  private

  def entity_params
    params.permit([:industry_association_slug, :company_slug])
  end

  def entity_param_for_type
    return entity_params[:company_slug] if entity_params[:company_slug]
    return entity_params[:industry_association_slug] if entity_params[:industry_association_slug]
  end

  def membership_params
    params.require(:membership).permit([
      :industry_association_id,
      :company_id
    ])
  end

  def edit_membership_params
    params.require(:membership).permit([:notes])
  end
end

app/views/memberships/_members_list.html.erb
<ul class='membershipList'>
  <% memberships_with_display_member.each do |membership, member| %>
    <li class='membershipList__membership'>
      <div>
        <h2><%= link_to member.name, member %></h2>

        <% if member.industry_association? %>
          <p class='entity__meta'>
            <%= render "industry_associations/collection_summary", entity: member %>
          </p>
        <% elsif member.company? %>
          <% if member.memberships.reject {|m| m.eql? membership }.any? %>
            <p class='entity__meta'>
              Also member of
              <strong>
                <%= member.memberships.reject {|m| m.eql? membership }.map { |m| m.industry_association.short_name_or_fallback }.join(', ') %>
              </strong>
            </p>
          <% end %>
        <% end %>

        <% if membership.notes.present? %>
          <div class='membershipList__notes'>
            <%= parse_and_sanitize_markdown(membership.notes) %>
          </div>
        <% end %>

        <% if current_researcher&.is_editor? %>
          <%= link_to 'Edit notes', edit_membership_path(membership, t: @entity&.class), class: 'editLink' %>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>

app/views/memberships/edit.html.erb
<%= content_for(:meta_title_front, "Edit membership") %>

<%= form_for(@membership, html: { class: 'form--entities' }) do |f| %>
  <% if @membership.errors.any? %>
    <div class="notification notification--error notification--formIntro">
      <p class="notification__text">We were unable to save this membership, because:</p>
      <ul>
        <% @membership.errors.full_messages.each do |msg| %>
          <li ><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <%= f.label(
      :notes,
      "Add a note about #{@membership.company.name}'s membership to #{@membership.industry_association.name}",
    )
    %>
    <p class='helperText'>
      What are the key things, like fees or board positions, to know about this membership?
    </p>
    <p class='helperText'>
      You can use
      <%= link_to 'Markdown formatting', 'https://en.wikipedia.org/wiki/Markdown#Example', title: 'Learn how to use Markdown formatting.' %>
      to add some structure and links.
    </p>
    <%= f.text_area(:notes, rows: 4) %>
  </fieldset>

  <%= hidden_field_tag(:lead_entity_type, @lead_entity_type) %>

  <%= f.submit 'Submit', class: 'input--submit' %>
<% end %>

app/views/memberships/index.html.erb
<% if @entity.industry_association? %>
  <%= content_for(:meta_title_front, "Members — #{@entity.name}") %>
<% else %>
  <%= content_for(:meta_title_front, "Memberships — #{@entity.name}") %>
<% end %>

<%= render(
  "application/breadcrumbs",
  steps: [
    (@entity.company? ? :companies : :industry_associations),
    @entity,
    :memberships
  ]
) %>

<div class='itemsPage'>
  <div class='itemsPage__header__container'>
    <header class='itemsPage__header'>
      <div class='itemsPage__header__content'>
        <h1>
          <span class='preHeading'><%= @entity.name %></span>
          <% if @entity.industry_association? %>
            Members
          <% else %>
            Industry Association Memberships
          <% end %>
        </h1>

        <% if current_researcher&.is_editor? %>
          <% if @entity.industry_association? %>
            <%= link_to 'Add a membership', new_industry_association_membership_path(@entity), title: "Add the companies that are members of #{@entity.name}", class: ('editLink' if @entity.members.any?) %>
          <% elsif @entity.company? %>
            <%= link_to 'Add a membership', new_company_membership_path(@entity), title: "Add the industry associations that #{@entity.name} belongs to.", class: ('editLink' if @entity.industry_associations.any?) %>
          <% end %>
        <% end %>
      </div>
      <%= render "entities/entities_nav", entity: @entity %>
  </header>
  </div>
  <section class='itemsPage__body'>
    <%= render(
      "members_list",
      memberships_with_display_member: @memberships_with_entities
    ) %>
  </section>
</div>

app/views/memberships/new.html.erb
<%= content_for(:meta_title_front, 'Add a new membership') %>

<%= link_to( '← Back',
             @return_to,
             title: 'Abandon any changes without saving and go back.',
             onclick: 'window.onbeforeunload = function() { return true; };',
             class: 'button--transparent') %>

<%= form_for([@entity, @membership], html: { class: 'form--memberships' }) do |f| %>
  <h1>
    Add a
    <% if @entity.is_a? Company %>
      industry association membership for <%= @entity.name %>
    <% elsif @entity.is_a? IndustryAssociation %>
      member to <%= @entity.short_name_or_fallback %>
    <% end %>
  </h1>

  <% if @membership.errors.any? %>
    <div class="notification notification--error notification--formIntro">
      <p class="notification__text">We were unable to save this membership, because:</p>
      <ul>
        <% @membership.errors.full_messages.each do |msg| %>
          <li ><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <% if @entity.is_a? Company %>
      <%= f.label(:industry_association_id, 'Industry association') %>
      <%= f.label(:industry_association_id, 'What organisation are they a member of? e.g. Minerals Council of Australia.', class: 'helperText') %>
      <%= f.collection_select(
        :industry_association_id,
        IndustryAssociation.order(:name).reject {|t| @entity.industry_associations.include? t },
        :id,
        :name,
        { prompt: true },
        { required: true }
      ) %>
    <% elsif @entity.is_a? IndustryAssociation %>
      <%= f.label(:company_id, 'Company') %>
      <%= f.label(:company_id, 'Which companies are members?', class: 'helperText') %>
      <%= f.collection_select(
        :company_id,
        Company.order(:name).reject {|c| @entity.members.include? c},
        :id,
        :name,
        { prompt: true },
        { required: true }
      ) %>
    <% end %>
  </fieldset>
  <%= f.submit 'Submit', class: 'input--submit' %>
<% end %>