config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :researchers
  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :items, only: [:show, :index, :new, :create, :edit, :update]

  resources :tags, only: [:index, :show, :edit, :update, :destroy], param: :name
  get 'tags/:name', to: 'tags#show', as: 'gutentag_tag'

  resources :entities, only: [:edit, :update, :new, :create], param: :slug

  resources :industry_associations, only: [:index, :show], param: :slug do
    resources :memberships, only: [:new, :create]
    resources :members, only: [:index], controller: 'memberships'
  end

  resources :companies, only: [:index, :show], param: :slug do
    resources :memberships, only: [:index, :new, :create]
  end

  resources :memberships, only: [:edit, :update]

  get 'staging', to: 'staging#index'

  namespace :staging do
    get 'dismissed', to: 'dismissed#index'

    resources :feeds, only: [:index] do
      post 'activate', on: :member, to: 'feeds#activate'
      post 'pause', on: :member, to: 'feeds#pause'
      post 'webhook', on: :member, to: 'feeds#webhook'
    end
  end

  post 'staging_items/:id/dismiss', to: 'staging#dismiss', as: 'dismiss_staging_item'

  namespace :api do
    namespace :v0 do
      resources :items, only: [:index]
    end
  end

  authenticate :researcher do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/entity.rb
class Entity < ApplicationRecord
  TYPES = ['IndustryAssociation', 'Company']

  has_many :items
  has_many :staging_items
  has_many :item_feeds

  validates :name, :slug, presence: true
  validates :name, :slug, uniqueness: true
  validates :short_name, uniqueness: true, allow_blank: true
  validate :slug_matches_format

  def company?
    is_a? Company
  end

  def industry_association?
    is_a? IndustryAssociation
  end

  def to_param
    slug
  end

  def short_name_or_fallback
    short_name.presence || name
  end

  def years_covered_by_items
    # FIXME: This only works effectively for IndustryAssociations
    years = [
      items.where.not(published_at: nil).order(:published_at).select('EXTRACT(YEAR FROM published_at)::integer').first&.date_part,
      items.where.not(published_at: nil).order(:published_at).select('EXTRACT(YEAR FROM published_at)::integer').last&.date_part
    ]
    years.compact!

    return years if years.size < 2
    (years.first..years.last).to_a
  end

  private

  def slug_matches_format
    return if slug.eql? slug&.parameterize
    errors.add(
      :slug,
      'must only contain lowercase letters, numbers, dashes, and have no spaces or other characters.'
    )
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action(:authenticate_researcher!)
  before_action(:authenticate_editor!)
  before_action :use_minimal_layout, only: [:new, :create, :edit, :update]

  def new
    @entity = Entity.new

    assign_return_to(@entity)
  end

  def create
    @entity = Entity.new(entity_params)

    assign_return_to(@entity)

    if @entity.save
      redirect_to @entity, notice: "Successfully created new entity"
    else
      flash.now[:error] = "We could not to save these changes."
      render :new
    end
  end

  def edit
    @entity = Entity.find_by!(slug: params[:slug])

    assign_return_to(@entity)
  end

  def update
    @entity = Entity.find_by!(slug: params[:slug])

    assign_return_to(@entity)

    if @entity.update(entity_params)
      redirect_to @entity, notice: "Successfully updated #{@entity.name}."
    else
      flash.now[:error] = "We could not to save these changes."
      render :edit
    end
  end

  private

  def entity_params
    params.require(:entity).permit([
      :name,
      :short_name,
      :description,
      :slug,
      :type
    ])
  end
end

app/views/entities/_company_memberships.html.erb
<h2 class='infoBox__heading'>Industry association memberships</h2>

<% if membership_entities.any? %>
  <p>
    <%= company.name %> is a member of
    <%= to_sentence membership_entities.map {|industry_association| "the #{link_to(industry_association.name, industry_association, title: "See the lobbying activities of the #{industry_association.name}")}".html_safe} %>.
  </p>

  <%= link_to 'View all memberships', company_memberships_path(company), title: "View all the industry associations that #{company.name} belongs to." %>
<% else %>
  <p>We're yet to list <%= company.name %>'s memberships. Please let us know of any.</p>
<% end %>

app/views/entities/_entities_nav.html.erb
<nav class='subNav'>
  <ul>
    <li class='subNav__item <%= 'subNav__item--current' if current_page?(entity)%>'>
      <%= link_to 'Public lobbying', entity, title: 'View our collection of this groups lobbying activites', class: "subNav__link" %>
    </li>
    <li class='subNav__item <%= 'subNav__item--current' if current_page?(company_memberships_path(entity)) || current_page?(industry_association_members_path(entity))%>'>
      <% if entity.company? %>
        <%= link_to 'Memberships', company_memberships_path(entity), title: "View all the industry associations that #{entity.name} belongs to.", class: "subNav__link" %>
      <% elsif entity.industry_association? %>
        <%= link_to 'Members', industry_association_members_path(entity), title: "View all companies that are members of #{entity.name}.", class: "subNav__link" %>
      <% end %>
    </li>
  </ul>
</nav>

app/views/entities/_industry_association_memberships.html.erb
<h2 class='infoBox__heading'>Who supports this lobbying?</h2>

<% if membership_entities.any? %>
  <p>
    <%= industry_association.short_name_or_fallback %>&rsquo;s members include
    <%= to_sentence membership_entities.map {|member| "#{link_to(member.name, member, title: "See the lobbying activities of #{member.name}")}".html_safe} %>.
  </p>

  <%= link_to "View all #{pluralize(industry_association.members.size, 'members')}", industry_association_members_path(industry_association), title: "View all companies that are members of #{industry_association.name}." %>
<% else %>
  <p>We're yet to list <%= industry_association.short_name_or_fallback %>'s members. Please pass on any information you have.</p>
<% end %>

app/views/entities/_items_results.html.erb
<header class='itemsResults__header'>
  <h2 class='itemsResults__title'>
    Public lobbying activities
    <% if include_industry_association_items %>
      by <%= entity.short_name_or_fallback %>
      and the industry associations they fund
    <% end %>
  </h2>

  <% if entity.is_a? Company %>
    <% if include_industry_association_items %>
      <%= link_to "View items from #{entity.short_name_or_fallback} only", company_path(entity, company_only: true), title: "Exclude lobbying activities by the industry associations #{entity.short_name_or_fallback} fund." %>
    <% else %>
      <%= link_to "Include lobbying by the industry associations #{entity.short_name_or_fallback} funds", entity, title: "Include lobbying activities by the industry associations #{entity.short_name_or_fallback} fund." %>
    <% end %>
  <% end %>

  <% if @tag %>
    <div class='infoBox infoBox--small'>
      <h3 class='infoBox__heading infoBox__heading--small'><%= @tag.name %></h3>
      <% if @tag.short_description.present? %>
        <div class='infoBox__content'>
          <%= @tag.short_description %>
          <%= link_to "read more", tag_path(@tag), title: "Read more about #{@tag.name}." %>
        </div>
      <% end %>
    </div>
  <% end %>
</header>

<%= render 'items/list', items: items, entity: entity %>

<%= will_paginate items, class: 'itemList__pagination' %>

app/views/entities/_list.html.erb
<h2><%= type %></h2>

<% if entities %>
  <ul class='entitiesList'>
    <% entities.each do |entity| %>
      <li>
        <%= link_to entity, class: 'entity' do %>
          <%= render entity, entity: entity %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/entities/edit.html.erb
<%= link_to( '← Back',
             @return_to,
             title: 'Abandon any changes without saving and go back.',
             onclick: 'window.onbeforeunload = function() { return true; };',
             class: 'button--transparent') %>

<%= form_for(@entity.becomes(Entity), html: { class: 'form--entities' }) do |f| %>
  <h1><%= @entity.name %></h1>

  <% if @entity.errors.any? %>
    <div class="notification notification--error notification--formIntro">
      <p class="notification__text">We were unable to save this entity, because:</p>
      <ul>
        <% @entity.errors.full_messages.each do |msg| %>
          <li ><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend>
      Describe the <%= @entity.short_name_or_fallback %>
    </legend>
    <p>
      Add a short description for people who don't know all the players.
      What are the key things to know about the <%= @entity.short_name_or_fallback %>?
    </p>

    <%= f.label(:description, 'Add a description') %>
    <p class='helperText'>
      You can use
      <%= link_to 'Markdown formatting', 'https://en.wikipedia.org/wiki/Markdown#Example', title: 'Learn how to use Markdown formatting.' %>
      to add some structure and links.
    </p>
    <%= f.text_area(:description, rows: 4) %>
  </fieldset>

  <%= f.submit 'Submit', class: 'input--submit' %>
<% end %>

app/views/entities/new.html.erb
<%= content_for(:meta_title_front, 'Add a new entity to track') %>

<%= link_to( '← Back',
             @return_to,
             title: 'Abandon any changes without saving and go back.',
             onclick: 'window.onbeforeunload = function() { return true; };',
             class: 'button--transparent') %>

<%= form_for(@entity.becomes(Entity), html: { class: 'form--entities' }) do |f| %>
  <h1>Add a new lobby group</h1>

  <% if @entity.errors.any? %>
    <div class="notification notification--error notification--formIntro">
      <p class="notification__text">We were unable to save this entity, because:</p>
      <ul>
        <% @entity.errors.full_messages.each do |msg| %>
          <li ><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <%= f.label(:name, 'Full name') %>
    <%= f.label(:name, 'The full name for the organisation, e.g. Minerals Council of Australia.', class: 'helperText') %>
    <%= f.text_field(:name, placeholder: 'e.g. Minerals Council of Australia', required: true) %>
    <% if @entity.errors[:name].any? %>
      <%= f.label(
        :slug,
        @entity.errors[:name].pop,
        class: 'helperText helperText--error'
      ) %>
    <% end %>
  </fieldset>

  <fieldset>
    <%= f.label(:type, 'What type of entity is this?') %>
    <%= f.select(
      :type,
      Entity::TYPES.map { |t| [t.underscore.humanize, t] },
      selected: (@entity&.type)
    ) %>
  </fieldset>

  <fieldset class='fieldgroup--short'>
    <%= f.label(:short_name, 'Short name') %>
    <%= f.label(:short_name, 'The abbreviation name for the organisation, e.g. MCA.', class: 'helperText') %>
    <%= f.text_field(:short_name, placeholder: 'e.g. MCA') %>
    <% if @entity.errors[:short_name].any? %>
      <%= f.label(
        :slug,
        @entity.errors[:short_name].pop,
        class: 'helperText helperText--error'
      ) %>
    <% end %>
  </fieldset>

  <fieldset class='fieldgroup--short'>
    <%= f.label(:slug, 'Slug') %>
    <%= f.label(:slug, "The string of characters used for the URL, e.g. #{content_tag(:code, 'mca')}.".html_safe, class: 'helperText') %>
    <%= f.text_field(:slug, placeholder: 'e.g. mca', required: true, class: 'input--slug') %>
    <% if @entity.errors[:slug].any? %>
      <%= f.label(
        :slug,
        @entity.errors[:slug].pop,
        class: 'helperText helperText--error'
      ) %>
    <% end %>
  </fieldset>

  <fieldset>
    <%= f.label(:description, 'Add a description') %>
    <p class='helperText'>
      Add a short description for people who don't know all the players.
      What are the key things to know about this group?
    </p>
    <p class='helperText'>
      You can use
      <%= link_to 'Markdown formatting', 'https://en.wikipedia.org/wiki/Markdown#Example', title: 'Learn how to use Markdown formatting.' %>
      to add some structure and links.
    </p>
    <%= f.text_area(:description, rows: 4) %>
  </fieldset>

  <%= f.submit 'Submit', class: 'input--submit' %>
<% end %>

app/views/entities/show.html.erb
<%= content_for(:meta_title_front, @entity.name) %>

<%= render(
  "application/breadcrumbs",
  steps: [
    (@entity.company? ? :companies : :industry_associations),
    @entity
  ]
) %>

<div class='itemsPage'>
  <div class='itemsPage__header__container'>
    <header class='itemsPage__header'>
      <div class='itemsPage__header__content'>
        <h1><%= @entity.name %></h1>
        <% if @entity.description.present? %>
          <div class='lede itemsPage__header__description'><%= parse_and_sanitize_markdown(@entity.description) %></div>
          <% if current_researcher&.is_editor? %>
            <%= link_to 'Edit', edit_entity_path(@entity), title: "Edit #{@entity.name}", class: 'editLink' %>
          <% end %>
        <% elsif current_researcher&.is_editor? %>
          <em>
            <%= link_to 'Add a description', edit_entity_path(@entity), title: "Edit #{@entity.name}" %> of <%= @entity.name %>,
            to give people some context when viewing this page.
          </em>
        <% end %>
      </div>
      <%= render "entities/entities_nav", entity: @entity %>
    </header>
  </div>

  <section class='itemsPage__body itemsSection'>
    <%= render(
      "entities/items_results",
      filters: @filters,
      items: @items,
      entity: @entity,
      include_industry_association_items: @include_industry_association_items
    ) %>

    <section class='itemsSection__membershipsSummary infoBox infoBox--light'>
      <% if @entity.company? %>
        <%= render("entities/company_memberships", company: @entity, membership_entities: @membership_entities) %>
      <% elsif @entity.industry_association? %>
        <%= render("entities/industry_association_memberships", industry_association: @entity, membership_entities: @membership_entities) %>
      <% end %>
    </section>
  </section>
</div>