config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :researchers
  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :items, only: [:show, :index, :new, :create, :edit, :update]

  resources :tags, only: [:index, :show, :edit, :update, :destroy], param: :name
  get 'tags/:name', to: 'tags#show', as: 'gutentag_tag'

  resources :entities, only: [:edit, :update, :new, :create], param: :slug

  resources :industry_associations, only: [:index, :show], param: :slug do
    resources :memberships, only: [:new, :create]
    resources :members, only: [:index], controller: 'memberships'
  end

  resources :companies, only: [:index, :show], param: :slug do
    resources :memberships, only: [:index, :new, :create]
  end

  resources :memberships, only: [:edit, :update]

  get 'staging', to: 'staging#index'

  namespace :staging do
    get 'dismissed', to: 'dismissed#index'

    resources :feeds, only: [:index] do
      post 'activate', on: :member, to: 'feeds#activate'
      post 'pause', on: :member, to: 'feeds#pause'
      post 'webhook', on: :member, to: 'feeds#webhook'
    end
  end

  post 'staging_items/:id/dismiss', to: 'staging#dismiss', as: 'dismiss_staging_item'

  namespace :api do
    namespace :v0 do
      resources :items, only: [:index]
    end
  end

  authenticate :researcher do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action(
    :authenticate_researcher!,
    unless: -> { ENV['PUBLIC_ACCESS'].eql?('true') && ['index'].include?(action_name) }
  )

  def index
    @industry_associations = IndustryAssociation.order(:name)
    @companies = Company.order(:name).where(promoted: true)
  end
end

app/views/home/index.html.erb
<div class='indexPage'>
  <header class='pageHeader'>
    <h1>Entities we watch</h2>
  </header>
  <div>
    <%= render "entities/list", type: 'Industry associations', entities: @industry_associations %>

    <%= render "entities/list", type: 'Companies', entities: @companies %>
    <%= link_to "See all #{pluralize(Company.count, 'company')}", companies_path, title: 'View the list of all companies in our records.' %>

    <% if current_researcher&.is_editor? %>
      <p>
        <%= link_to 'Add a new entity to track', new_entity_path, class: 'button--transparent' %>
      </p>
    <% end %>
  </div>
</div>