config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :researchers
  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :items, only: [:show, :index, :new, :create, :edit, :update]

  resources :tags, only: [:index, :show, :edit, :update, :destroy], param: :name
  get 'tags/:name', to: 'tags#show', as: 'gutentag_tag'

  resources :entities, only: [:edit, :update, :new, :create], param: :slug

  resources :industry_associations, only: [:index, :show], param: :slug do
    resources :memberships, only: [:new, :create]
    resources :members, only: [:index], controller: 'memberships'
  end

  resources :companies, only: [:index, :show], param: :slug do
    resources :memberships, only: [:index, :new, :create]
  end

  resources :memberships, only: [:edit, :update]

  get 'staging', to: 'staging#index'

  namespace :staging do
    get 'dismissed', to: 'dismissed#index'

    resources :feeds, only: [:index] do
      post 'activate', on: :member, to: 'feeds#activate'
      post 'pause', on: :member, to: 'feeds#pause'
      post 'webhook', on: :member, to: 'feeds#webhook'
    end
  end

  post 'staging_items/:id/dismiss', to: 'staging#dismiss', as: 'dismiss_staging_item'

  namespace :api do
    namespace :v0 do
      resources :items, only: [:index]
    end
  end

  authenticate :researcher do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/controllers/tags_controller.rb
require 'csv_serializer'

class TagsController < ApplicationController
  before_action(
    :authenticate_researcher!,
    unless: -> { ENV['PUBLIC_ACCESS'].eql?('true') && ['show', 'index'].include?(action_name) }
  )
  before_action(:authenticate_editor!, except: [:index, :show])
  before_action :use_minimal_layout, only: [:edit, :update]

  def index
    @tags = Gutentag::Tag.order(taggings_count: :desc)
  end

  def show
    @tag = Gutentag::Tag.find_by_name_param!(tag_params[:name])
    @context = @tag
    @items = Item.tagged_with(names: [@tag.name]).left_joins(:document).order('documents.published_at DESC, items.created_at DESC').includes(:tags, :entity, :document)

    respond_to do |format|
      format.html do
        @days_with_items = @items.group_by { |i| i.document.published_at }
        @include_industry_association_items = true
      end

      format.csv do
        send_data(
          CsvSerializer::Item.serialize(@items),
          filename: CsvSerializer::Item.file_name(@tag.name.parameterize(preserve_case: true)),
          type: 'text/csv'
        )
      end
    end
  end

  def edit
    @tag = Gutentag::Tag.find_by_name_param!(tag_params[:name])

    assign_return_to(@tag)
  end

  def update
    @tag = Gutentag::Tag.find_by_name_param!(tag_params[:name])

    assign_return_to(@tag)

    if @tag.update(edit_tag_params)
      redirect_to tag_path(@tag), notice: "Successfully updated tag"
    else
      flash.now[:error] = "We could not to save these changes."
      render :edit
    end
  end

  def destroy
    @tag = Gutentag::Tag.find_by_name_param!(tag_params[:name])

    if @tag.destroy!
      redirect_to tags_path, notice: "Successfully deleted tag '#{@tag.name}' with #{@tag.taggings_count} connections"
    else
      flash.now[:error] = "We could not to delete this tag."
      render :edit
    end
  end

  private

  def tag_params
    params.permit(:name)
  end

  def edit_tag_params
    params.require(:gutentag_tag).permit(:name, :description)
  end
end

app/views/tags/edit.html.erb
<%= content_for(:meta_title_front, "Edit Tag") %>

<%= link_to( '← Back',
             @return_to,
             title: 'Abandon any changes without saving and go back.',
             onclick: 'window.onbeforeunload = function() { return true; };',
             class: 'button--transparent') %>

<%= form_for(@tag, url: tag_path(@tag.name.tr(' ', '+')), html: { class: 'form--entities' }) do |f| %>
  <h1>Edit tag</h1>

  <% if @tag.errors.any? %>
    <div class="notification notification--error notification--formIntro">
      <p class="notification__text">We were unable to save this tag, because:</p>
      <ul>
        <% @tag.errors.full_messages.each do |msg| %>
          <li ><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <%= f.label(:name, 'Tag name') %>
    <%= f.label(:name, 'We prefer precise names. Use "Kyoto carryover credits" over just "Kyoto" for that concept, for example.', class: 'helperText') %>
    <%= f.text_field(:name, placeholder: 'e.g. "Tania Constable", or "ALP Election 2019 Climate Policy Announcement"', required: true) %>
    <% if @tag.errors[:name].any? %>
      <%= f.label(
        :name,
        @tag.errors[:name].pop,
        class: 'helperText helperText--error'
      ) %>
    <% end %>
  </fieldset>

  <fieldset>
    <%= f.label(:description) %>
    <p class='helperText'>
      What are the key things to know about this tag and the items it collects?
    </p>
    <p class='helperText'>
      You can use
      <%= link_to 'Markdown formatting', 'https://en.wikipedia.org/wiki/Markdown#Example', title: 'Learn how to use Markdown formatting.' %>
      to add some structure and links.
    </p>
    <%= f.text_area(:description, rows: 4) %>
  </fieldset>

  <%= f.submit 'Submit', class: 'input--submit' %>
<% end %>

<div class='form--entities'>
  <h2>Danger zone</h2>
  <p>
    Deleting this tag removes it, it's description,
    and all <strong><%= @tag.taggings_count %> existing connections to our collection</strong>.
    It won't be straight forward to recover.
  </p>
  <p>
    <%= button_to(
      'Delete tag',
      @tag,
      action: :destroy,
      method: :delete,
      data: { confirm: 'Are you sure?' },
      class: 'button button--danger'
    ) %>
  </p>
</div>

app/views/tags/index.html.erb
<%= content_for(:meta_title_front, 'Tags') %>

<div class='indexPage'>
  <header class='pageHeader'>
    <h1>Tags</h1>
  </header>
  <div>
    <ul>
      <% @tags.each do |tag| %>
        <li>
          <%= link_to tag.name, tag %>
          (<%= pluralize(tag.taggings_count, 'item') %>)
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/tags/show.html.erb
<%= content_for(:meta_title_front, "#{@tag.name}") %>

<%= render('application/breadcrumbs', steps: [:tags, @tag]) %>

<div class='itemsPage'>
  <div class='itemsPage__header__container'>
    <header class='itemsPage__header'>
      <h1>
        <span class='preHeading'>Lobbying tagged</span>
        <%= @tag.name %>
      </h1>

      <% if @tag.description.present? %>
        <div class='contentPage__longDescription'>
          <%= parse_and_sanitize_markdown(@tag.description) %>
        </div>
      <% end %>

      <% if current_researcher&.is_editor? %>
        <p><%= link_to 'Edit tag', edit_tag_path(@tag), title: 'Change the name and description of this tag.', class: 'editLink' %></p>
      <% end %>
    </header>
  </div>

  <section class='itemsPage__body itemsSection'>
    <header class='itemsResults__header'>
      <h2>Related lobbying activity</h2>
      <p><%= pluralize(@items.count, 'item') %></p>
    </header>
    <%= render 'items/list', items: @items, entity: nil %>
  </section>
</div>